logging:
  config: classpath:logback.xml
  path : var/log/application

management:
  port: 8090
  security:
    enabled: false
    roles:
      - ADMIN
  context-path: /actuator
  endpoints:
    web:
      exposure:
        include: "*"