apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hellozcp
  labels:
    app: hellozcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellozcp
  template:
    metadata:
      labels:
        app: hellozcp
    spec:
      containers:
      - name: hellozcp
        image: earth1223/hellozcp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 10 
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /timeout?timeout=2
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: harbor-secret
  strategy:
    type: RollingUpdate
