apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hellozcp
  labels:
    app: hellozcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellozcp
  template:
    metadata:
      labels:
        app: hellozcp
    spec:
      containers:
      - name: hellozcp
        image: earth1223/hellozcp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 10 
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      imagePullSecrets:
      - name: pri-harbor-secret
      volumes:  
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
  strategy:
    type: RollingUpdate
